In [18]:
import pandas as pd
import numpy as np

In [19]:
df = pd.read_csv(r"C:\Users\solom\OneDrive\Desktop\econ206_final_project\japan_data_cleaned.csv")
# removing rows < 1976 (No savings rate data)
df = df[df['year'] >= 1976]
df.head(10)
# column meanings: 
# iso - ISO 3166-1 alpha-3 country code
# year - the year of the observation
# Real output (rgdpo)
# Population (pop)
# Capital stock (rnna)
# Labor share (labsh)
# Depreciation rate (delta)
# Savings Rate (savings_rate)

,iso3,Country,year,delta,labsh,pop,rgdpo,rnna,savings_rate
0,JPN,Japan,1976,0.033833,0.617359,114.502795,2140760.25,8684773,35.392825
1,JPN,Japan,1977,0.033521,0.620946,115.574277,2288072.75,9251136,35.259136
2,JPN,Japan,1978,0.033337,0.611577,116.576944,2460841.75,9869457,35.474432
3,JPN,Japan,1979,0.033328,0.607692,117.521556,2625492.00,10512650,34.508197
4,JPN,Japan,1980,0.033443,0.609879,118.358756,2778892.00,11087465,34.235397
5,JPN,Japan,1981,0.033580,0.611526,118.994053,2771451.00,11661513,34.611069
6,JPN,Japan,1982,0.033680,0.613019,119.485775,2730068.75,12206848,33.390769
7,JPN,Japan,1983,0.033752,0.615773,119.948947,2694770.75,12716322,32.961817
8,JPN,Japan,1984,0.033893,0.606810,120.384394,2713529.00,13244571,33.718822
9,JPN,Japan,1985,0.034141,0.595854,120.832163,2794807.25,13826276,34.353794

In [20]:
# calculating average population growth rate (n), depreciation rate (δ), saving rate (σ), and labor share (1 − α) 
df['pop_growth'] = df['pop'].pct_change()
n = df['pop_growth'].mean()
delta = df['delta'].mean()
sigma = df['savings_rate'].mean()
alpha = 1 - df['labsh'].mean()  

print(f"Average population growth rate (n): {n}")
print(f"Average depreciation rate (δ): {delta}")
print(f"Average saving rate (σ): {sigma}")
print(f"Average labor share (1 − α): {alpha}")

Average population growth rate (n): 0.0017659720785368471
Average depreciation rate (δ): 0.037779132
Average saving rate (σ): 29.769919410416662
Average labor share (1 − α): 0.4220788466041666

In [21]:
# Constructing the per-capita capital, kData, using the data on capital stock and population over time.
df['k_t'] = df['rnna'] / df['pop']
df.head()

,iso3,Country,year,delta,labsh,pop,rgdpo,rnna,savings_rate,pop_growth,k_t
0,JPN,Japan,1976,0.033833,0.617359,114.502795,2140760.25,8684773,35.392825,NaN,75847.694373
1,JPN,Japan,1977,0.033521,0.620946,115.574277,2288072.75,9251136,35.259136,0.009358,80044.939412
2,JPN,Japan,1978,0.033337,0.611577,116.576944,2460841.75,9869457,35.474432,0.008676,84660.453957
3,JPN,Japan,1979,0.033328,0.607692,117.521556,2625492.00,10512650,34.508197,0.008103,89452.951082
4,JPN,Japan,1980,0.033443,0.609879,118.358756,2778892.00,11087465,34.235397,0.007124,93676.761861